### ISSUE TITLE
Change API Docs to Stoplight

### ISSUE THREAD

**Issue by gy-toxyc** [GY-CODING/api-docs#1]
The purpose of this issue is to implement a new API Reference documentation in Stoplight using YAML and OAS (OpenAPI Specification v3.1.0).

## Tasks
- [x] Set CI/CD between GitHub Actions and Stoplight.
- [x] Implement the basic structure.
- [x] Implement schemas, components, responses and error responses, covering almost everything from our API.

<br>

In order for this issue to be closed, all tasks should be completed.

**Comment by gy-toxyc** [comment]
We are not considering refactoring and giving better detail to the API Reference right now, as we are not considering the migration from our Postman API Docs to this new Stoplight API Docs at the moment. It will be consider in a close future, but not right now.

**Comment by gy-toxyc** [comment]
Migrated to Stoplight, this change lead to the following update on the API Gateway:
